[project]
name = "pdf-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=6.1.0",
    "openai>=2.11.0",
    "pypdf>=6.4.2",
]
